import 'package:equatable/equatable.dart';

/// Represents an AI-generated insight or suggestion.
///
/// This class encapsulates a message generated by the AI, along with optional
/// actions, such as a button with a navigation route.
class AiInsight extends Equatable {
  /// The main message of the insight.
  final String message;
  /// The text to display on the action button. If null, no button is shown.
  final String? buttonText;
  /// The named route to navigate to when the button is pressed.
  final String? navigationRoute;
  /// The arguments to pass to the navigation route.
  final dynamic navigationArguments;

  /// Creates a new instance of [AiInsight].
  ///
  /// The [message] is required. The other parameters are optional.
  const AiInsight({
    required this.message,
    this.buttonText,
    this.navigationRoute,
    this.navigationArguments,
  });

  @override
  List<Object?> get props => [message, buttonText, navigationRoute, navigationArguments];
}
