import 'package:advisor_desk/presentation/common/theme/share_card_themes.dart';
import 'package:flutter/material.dart';
import 'package:advisor_desk/core/constants/app_constants.dart';
import 'package:advisor_desk/domain/entities/monthly_summary.dart';
import 'package:advisor_desk/domain/entities/profile.dart';
import 'package:intl/intl.dart';

class PerformanceShareCard extends StatelessWidget {
  final MonthlySummary summary;
  final Profile profile;
  final ShareCardTheme theme;

  const PerformanceShareCard({
    Key? key,
    required this.summary,
    required this.profile,
    required this.theme,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final formatter = NumberFormat('#,##0.00');

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: theme.backgroundGradient,
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.2),
            blurRadius: 15,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Image.asset('assets/icon/app_icon.png', width: 36, height: 36),
              const SizedBox(width: 12),
              Text(
                AppConstants.appName,
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: theme.textColor,
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),
          Text(
            'Monthly Performance',
            style: TextStyle(
              fontSize: 26,
              fontWeight: FontWeight.bold,
              color: theme.textColor,
            ),
          ),
          Text(
            summary.formattedMonthYear,
            style: TextStyle(
              fontSize: 18,
              color: theme.textColor.withOpacity(0.8),
            ),
          ),
          if (profile.name != null) ...[
            const SizedBox(height: 8),
            Text(
              profile.name!,
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.w600,
                color: theme.textColor,
              ),
            ),
          ],
          const SizedBox(height: 24),
          _buildInfoRow(
            context,
            Icons.timer_outlined,
            'Total Login Hours',
            '${formatter.format(summary.totalLoginHours)} hrs',
          ),
          _buildInfoRow(
            context,
            Icons.phone_in_talk_outlined,
            'Total Calls',
            summary.totalCalls.toString(),
          ),
          _buildInfoRow(
            context,
            Icons.star_border_rounded,
            'CSAT Score',
            '${summary.csatSummary?.monthlyCSATPercentage.toStringAsFixed(2) ?? 'N/A'}%',
          ),
          _buildInfoRow(
            context,
            Icons.check_circle_outline_rounded,
            'CQ Score',
            '${summary.cqSummary?.monthlyAverageCQ.toStringAsFixed(2) ?? 'N/A'}%',
          ),
          const SizedBox(height: 12),
          Divider(color: theme.textColor.withOpacity(0.2)),
          const SizedBox(height: 12),
          _buildSalaryRow(
            context,
            Icons.account_balance_wallet_outlined,
            'Net Salary',
            '₹ ${formatter.format(summary.netSalary)}',
          ),
          const SizedBox(height: 24),
          Center(
            child: Text(
              'Generated by Advisor Desk',
              style: TextStyle(
                fontSize: 12,
                fontStyle: FontStyle.italic,
                color: theme.footerTextColor,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInfoRow(BuildContext context, IconData icon, String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        children: [
          Icon(icon, size: 22, color: theme.iconColor),
          const SizedBox(width: 16),
          Text(
            label,
            style: TextStyle(fontSize: 16, color: theme.textColor),
          ),
          const Spacer(),
          Text(
            value,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: theme.textColor,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSalaryRow(BuildContext context, IconData icon, String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        children: [
          Icon(icon, size: 28, color: theme.iconColor),
          const SizedBox(width: 16),
          Text(
            label,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w600,
              color: theme.textColor,
            ),
          ),
          const Spacer(),
          Text(
            value,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: theme.textColor,
            ),
          ),
        ],
      ),
    );
  }
}
