class StringsHinglish {
  static const Map<String, String> data = {
    // Settings
    'settings_title': 'Settings (Set-weting)',
    'general_section': 'AAM BAATEIN (General)',
    'advisor_ai_section': 'ADVISOR AI (Smart Dost)',
    'updates_section': 'NAYA KYA HAI? (Updates)',
    'data_section': 'DATA KA KHEL',
    'preferences_section': 'APNI PASAND (Preferences)',
    'security_section': 'SURAKSHA (Security)',
    'app_version': 'App Ka Version',
    'about_app': 'App Ke Baare Mein',
    'clear_chat_history': 'Purani Baatein Bhool Jao (Clear Chat)',
    'whats_new': "Naya Kya Aaya Hai?",
    'backup_data': 'Data Sambhal Lo (Backup)',
    'restore_data': 'Wapas Laao Data (Restore)',
    'salary_parameters': 'Salary Ka Hisaab',
    'theme_appearance': 'Rang-Roop (Theme)',
    'customize_dashboard': 'Dashboard Sajao',
    'app_lock': 'Taala Lagao (App Lock)',
    'app_lock_settings': 'Taale Ki Settings',
    'privacy_policy': 'Privacy Ki Baatein',
    'rate_app': 'App Ko Stars Do',
    'language': 'Bhasha (Language)',
    'select_language': 'Bhasha Chuno',
    'cancel': 'Rehne Do',
    'save_profile': 'Profile Save Karo',
    'manage_users': 'Users Sambhalo',

    // Dashboard
    'dashboard_total_calls': 'Total Calls (Kitne kiye?)',
    'dashboard_login_hours': 'Login Hours (Kitna kaam?)',
    'dashboard_net_salary': 'Haath Mein Kitna Aaya (Net Salary)',

    // Add Entry
    'add_new_entry': 'Nayi Entry Daalo',
    'edit_entry': 'Entry Sudharo',
    'daily_entry_tab': 'Roz Ka Kaam',
    'csat_entry_tab': 'CSAT Entry',
    'cq_entry_tab': 'CQ Entry',
    'select_date': 'Taareekh Chuno',
    'login_duration': 'Login Time (Kitni der?)',
    'hours_label': 'Ghante (Hrs)',
    'minutes_label': 'Minute (Mins)',
    'seconds_label': 'Second (Secs)',
    'performance_section': 'Performance (Kaisa raha din?)',
    'total_calls_label': 'Total Calls',
    'advanced_options': 'Advanced Options',
    'custom_per_call_rate': 'Alag Rate Lagana Hai?',
    'override_default_rate': 'Is entry ke liye rate badlo',
    'custom_rate_label': 'Naya Rate (₹)',
    'update_entry_btn': 'Entry Update Karo',
    'save_daily_entry_btn': 'Entry Save Karo',
    'delete_entry_btn': 'Entry Hatao (Delete)',
    'confirm_delete_title': 'Pakka Delete Karna Hai?',
    'confirm_delete_message': 'Yeh entry wapas nahi aayegi. Soch lo!',
    'delete': 'Uda Do (Delete)',
    'required_error': 'Yeh zaroori hai',
    'invalid_rate_error': 'Sahi rate daalo',
    'entry_added_success': 'Badhai ho! Entry save ho gayi.',
    'entry_updated_success': 'Entry update ho gayi!',
    'entry_deleted_success': 'Entry delete kar di gayi.',
    'failed_save_entry': 'Oho! Save nahi ho paya.',

    // Add CSAT
    'add_csat_entry': 'CSAT Entry Jodo',
    'edit_csat_entry': 'CSAT Entry Theek Karo',
    'date_label': 'Taareekh',
    't2_count_label': 'T2 Count (Achha Feedback)',
    'b2_count_label': 'B2 Count (Kharaab Feedback)',
    'n_count_label': 'N Count (Theek-Thaaak)',
    'enter_t2_hint': 'T2 count daalo',
    'enter_b2_hint': 'B2 count daalo',
    'enter_n_hint': 'N count daalo',
    'preview_section': 'Jhalak (Preview)',
    'total_survey_hits': 'Total Survey Hits',
    't2_score': 'T2 Score',
    'b2_score': 'B2 Score',
    'n_score': 'N Score',
    'csat_percentage': 'CSAT %',
    'csat_needs_improvement': '60% se kam hai! Thoda dhyaan do.',
    'update_csat_btn': 'CSAT Update Karo',
    'save_csat_btn': 'CSAT Save Karo',
    'csat_added_success': 'CSAT save ho gaya!',
    'csat_updated_success': 'CSAT update ho gaya!',
    'csat_deleted_success': 'CSAT uda diya!',
    'failed_save_csat': 'CSAT save nahi hua.',
    'confirm_delete_csat_message': 'Pakka yeh CSAT entry hatani hai?',

    // Add CQ
    'add_cq_entries': 'CQ Entries Jodo',
    'update_cq_entry': 'CQ Entry Update Karo',
    'select_audits_today': 'Aaj kitne audits huye?',
    'number_of_audits_label': 'Audits ki Sankhya',
    'add_entries_btn': 'Entries Jodo',
    'entry_label': 'Entry',
    'cq_percentage_label': 'CQ %',
    'cq_percentage_hint': 'CQ % daalo (0-100)',
    'enter_percentage_error': 'Percentage daalna padega',
    'valid_number_error': 'Sahi number daalo',
    'cq_added_success': 'CQ entry save ho gayi!',
    'cq_updated_success': 'CQ entry update ho gayi!',
    'cq_deleted_success': 'CQ entry delete ho gayi!',

    // FAB Menu
    'add_daily_entry_fab': 'Roz Ka Kaam Jodo',
    'set_goals_fab': 'Goals Set Karo',
    'chat_ai_fab': 'AI Dost Se Baat Karo',

    // Dashboard Cards
    'total_calls_card': 'Total Calls',
    'non_billable_calls_card': 'Non-billable Calls',
    'total_login_hours_card': 'Total Login Hours',
    'avg_login_hours_card': 'Avg. Login Hours',
    'avg_calls_card': 'Avg. Calls',
    'csat_score_card': 'CSAT Score',
    'cq_score_card': 'CQ Score',
    'net_salary_card': 'Net Salary',
    'forecaster_card': 'Forecaster (Bhavishya)',
    'project_salary_subtitle': 'Salary Estimate Karo',
    'login_days_card': 'Login Days',

    // Goals Dialog
    'set_monthly_goals_title': 'Mahine Ka Target Set Karo',
    'asking_ai_suggestions': 'AI se pooch raha hoon...',
    'ask_ai_btn': 'AI Se Ideas Lo',
    'target_login_hours_label': 'Target Login Hours (Max 570)',
    'target_call_count_label': 'Target Call Count',
    'enter_target_hours_error': 'Hours daalna zaroori hai',
    'hours_exceed_error': '570 se zyada hours nahi ho sakte',
    'enter_target_calls_error': 'Calls daalna zaroori hai',
    'save_btn': 'Save Karo',

    // Empty State
    'no_data_month': 'Is mahine ka koi data nahi hai.',
    'unknown_error': 'Kuch gadbad ho gayi.',

    // Profile Screen
    'edit_profile_title': 'Profile Edit Karo',
    'profile_title': 'Mera Profile',
    'name_label': 'Naam',
    'not_set_label': 'Set Nahi Hai',
    'company_label': 'Company',
    'manage_users_label': 'Users Sambhalo',
    'enter_name_hint': 'Apna naam likho',
    'company_name_label': 'Company Ka Naam',
    'enter_company_hint': 'Apni company likho',
    'name_company_empty_error': 'Naam aur Company dono zaroori hain.',

    // User Management
    'manage_users_title': 'Users Sambhalo',
    'active_session_label': 'Abhi Yehi User Hai',
    'switch_btn': 'Badlo (Switch)',
    'add_user_tooltip': 'Naya User Jodo',
    'switch_user_title': 'User Badalna Hai?',
    'switch_user_message': 'Kya aap {userName} par switch karna chahte hain?',
    'delete_user_title': 'User Delete Karein',
    'delete_user_message': 'Kya aap {userName} ko delete karna chahte hain? Yeh wapas nahi aayega.',
    'add_new_user_title': 'Naya User Jodo',
    'user_name_label': 'User Ka Naam',
    'enter_user_name_hint': 'Naam likho',
    'add_btn': 'Jodo (Add)',
  };
}
