class StringsEn {
  static const Map<String, String> data = {
    // Settings
    'settings_title': 'Settings',
    'general_section': 'GENERAL',
    'advisor_ai_section': 'ADVISOR AI',
    'updates_section': 'UPDATES',
    'data_section': 'DATA',
    'preferences_section': 'PREFERENCES',
    'security_section': 'SECURITY & PRIVACY',
    'app_version': 'App Version',
    'about_app': 'About App',
    'clear_chat_history': 'Clear Chat History',
    'whats_new': "What's New",
    'backup_data': 'Backup Data',
    'restore_data': 'Restore Data',
    'salary_parameters': 'Salary Parameters',
    'theme_appearance': 'Theme & Appearance',
    'customize_dashboard': 'Customize Dashboard',
    'app_lock': 'App Lock',
    'app_lock_settings': 'App Lock Settings',
    'privacy_policy': 'Privacy Policy',
    'rate_app': 'Rate the App',
    'language': 'Language',
    'select_language': 'Select Language',
    'cancel': 'Cancel',
    'save_profile': 'Save Profile',
    'manage_users': 'Manage Users',
    'share_app': 'Share this App',
    'share_app_text': '🚀 Track your performance like a pro with Advisor Desk! 📈\n\nManage your CSAT, CQ, and daily performance metrics effortlessly. Stay organized and achieve your goals.\n\nDownload Advisor Desk now:\nhttps://play.google.com/store/apps/details?id=com.suvojeet.advisordesk',

    // Dashboard
    'dashboard_total_calls': 'Total Calls',
    'dashboard_login_hours': 'Login Hours',
    'dashboard_net_salary': 'Net Salary',

    // Add Entry
    'add_new_entry': 'Add New Entry',
    'edit_entry': 'Edit Entry',
    'daily_entry_tab': 'Daily Entry',
    'csat_entry_tab': 'CSAT Entry',
    'cq_entry_tab': 'CQ Entry',
    'select_date': 'Select Date',
    'login_duration': 'Login Duration',
    'hours_label': 'Hours',
    'minutes_label': 'Minutes',
    'seconds_label': 'Seconds',
    'performance_section': 'Performance',
    'total_calls_label': 'Total Calls',
    'advanced_options': 'Advanced Options',
    'custom_per_call_rate': 'Custom Per Call Rate',
    'override_default_rate': 'Override default rate for this entry',
    'custom_rate_label': 'Custom Rate (₹)',
    'update_entry_btn': 'Update Entry',
    'save_daily_entry_btn': 'Save Daily Entry',
    'delete_entry_btn': 'Delete Entry',
    'confirm_delete_title': 'Confirm Delete',
    'confirm_delete_message': 'Are you sure you want to delete this entry? This action cannot be undone.',
    'delete': 'Delete',
    'required_error': 'Required',
    'invalid_rate_error': 'Invalid rate',
    'entry_added_success': 'Entry added successfully!',
    'entry_updated_success': 'Entry updated successfully!',
    'entry_deleted_success': 'Entry deleted successfully!',
    'failed_save_entry': 'Failed to save entry',

    // Add CSAT
    'add_csat_entry': 'Add CSAT Entry',
    'edit_csat_entry': 'Edit CSAT Entry',
    'date_label': 'Date',
    't2_count_label': 'T2 Count (Positive Feedback)',
    'b2_count_label': 'B2 Count (Negative Feedback)',
    'n_count_label': 'N Count (Neutral Feedback)',
    'enter_t2_hint': 'Enter T2 count',
    'enter_b2_hint': 'Enter B2 count',
    'enter_n_hint': 'Enter N count',
    'preview_section': 'Preview',
    'total_survey_hits': 'Total Survey Hits',
    't2_score': 'T2 Score',
    'b2_score': 'B2 Score',
    'n_score': 'N Score',
    'csat_percentage': 'CSAT Percentage',
    'csat_needs_improvement': 'CSAT below 60% - Needs Improvement',
    'update_csat_btn': 'Update CSAT Entry',
    'save_csat_btn': 'Add CSAT Entry',
    'csat_added_success': 'CSAT Entry saved successfully!',
    'csat_updated_success': 'CSAT Entry updated successfully!',
    'csat_deleted_success': 'CSAT Entry deleted successfully!',
    'failed_save_csat': 'Failed to save CSAT entry.',
    'confirm_delete_csat_message': 'Are you sure you want to delete this CSAT entry? This action cannot be undone.',

    // Add CQ
    'add_cq_entries': 'Add CQ Entries',
    'update_cq_entry': 'Update CQ Entry',
    'select_audits_today': 'Select the number of audits Today',
    'number_of_audits_label': 'Number of Audits',
    'add_entries_btn': 'Add Entries',
    'entry_label': 'Entry',
    'cq_percentage_label': 'CQ Percentage',
    'cq_percentage_hint': 'Enter CQ percentage (0-100)',
    'enter_percentage_error': 'Please enter percentage',
    'valid_number_error': 'Please enter a valid number',
    'cq_added_success': 'CQ entry added successfully!',
    'cq_updated_success': 'CQ entry updated successfully!',
    'cq_deleted_success': 'CQ entry deleted successfully!',

    // FAB Menu
    'add_daily_entry_fab': 'Add Daily Entry',
    'set_goals_fab': 'Set Goals',
    'chat_ai_fab': 'Chat with Advisor Desk AI',

    // Dashboard Cards
    'total_calls_card': 'Total Calls',
    'non_billable_calls_card': 'Non-billable Calls',
    'total_login_hours_card': 'Total Login Hours',
    'avg_login_hours_card': 'Avg. Login Hours',
    'avg_calls_card': 'Avg. Calls',
    'csat_score_card': 'CSAT Score',
    'cq_score_card': 'CQ Score',
    'net_salary_card': 'Net Salary',
    'forecaster_card': 'Forecaster',
    'project_salary_subtitle': 'Project Salary',
    'login_days_card': 'Login Days',

    // Goals Dialog
    'set_monthly_goals_title': 'Set Monthly Goals',
    'asking_ai_suggestions': 'Asking AI for suggestions...',
    'ask_ai_btn': 'Ask AI for Suggestions',
    'target_login_hours_label': 'Target Login Hours (Max 570)',
    'target_call_count_label': 'Target Call Count',
    'enter_target_hours_error': 'Please enter target hours',
    'hours_exceed_error': 'Hours cannot exceed 570',
    'enter_target_calls_error': 'Please enter target calls',
    'save_btn': 'Save',

    // Empty State
    'no_data_month': 'No data available for this month.',
    'unknown_error': 'An unknown error occurred.',

    // Profile Screen
    'edit_profile_title': 'Edit Profile',
    'profile_title': 'Profile',
    'name_label': 'Name',
    'not_set_label': 'Not Set',
    'company_label': 'Company',
    'manage_users_label': 'Manage Users',
    'enter_name_hint': 'Enter your name',
    'company_name_label': 'Company Name',
    'enter_company_hint': 'Enter your company',
    'name_company_empty_error': 'Name and Company Name cannot be empty.',

    // User Management
    'manage_users_title': 'Manage Users',
    'active_session_label': 'Active Session',
    'switch_btn': 'Switch',
    'add_user_tooltip': 'Add User',
    'switch_user_title': 'Switch User',
    'switch_user_message': 'Are you sure you want to switch to {userName}? The app will reload with their data.',
    'delete_user_title': 'Delete User',
    'delete_user_message': 'Are you sure you want to delete {userName}? This action cannot be undone.',
    'add_new_user_title': 'Add New User',
    'user_name_label': 'User Name',
    'enter_user_name_hint': 'Enter name',
    'add_btn': 'Add',

    // Daily Entries Section
    'daily_entries_title': 'Daily Entries',
    'no_entries_month': 'No entries for this month.',

    // Monthly Goals Section
    'monthly_goals_title': 'Monthly Goals',
    'edit_btn': 'Edit',
    'login_hours_label': 'Login Hours',
    'calls_label': 'Calls',
    'remaining_hours_goal': 'Remaining Hours to Goal:',
    'remaining_calls_goal': 'Remaining Calls to Goal:',
    'daily_avg_hours_needed': 'Daily Avg. Hours Needed:',
    'daily_avg_calls_needed': 'Daily Avg. Calls Needed:',
    'remaining_calls_today': 'Remaining Calls for Today:',
    'remaining_hours_today': 'Remaining Hours for Today:',
    'salary_projection_title': 'Salary Projection',
    'current_salary_label': 'Current Salary',
    'projected_salary_label': 'Projected Salary (at 100% goal)',
    'congratulations_title': 'Congratulations!',
    'goals_achieved_message': 'You have successfully achieved your monthly goals.',
    'view_targets_btn': 'View Targets',
    'get_ai_suggestions_btn': 'Get AI Suggestions',

    // Salary Section
    'salary_details_title': 'Salary Details',
    'billable_calls_label': 'Billable Calls',
    'base_salary_label': 'Base Salary',
    'bonus_amount_label': 'Bonus Amount',
    'csat_bonus_label': 'CSAT Bonus',
    'gross_salary_label': 'Gross Salary',
    'tds_deduction_label': 'TDS Deduction',

    // Summary Section
    'monthly_summary_title': 'Monthly Summary',
    'average_daily_login_hours': 'Average Daily Login Hours',
    'average_daily_calls': 'Average Daily Calls',
  };
}
